### ISSUE TITLE
#Bug: Log-level always info at higher level.

### ISSUE THREAD

**Issue by ghost** [deep-compute/docker-file-log-driver#4]
#### Read-Me:
* We are writing docker-logs to outside the docker using `docker-file-log-driver` but if we got a `debug` log at the higher level we are getting `info` log only.
![screen shot 2018-05-07 at 2 48 55 pm](https://user-images.githubusercontent.com/16955073/39694776-0e30701e-5206-11e8-9c8a-e089c18c8bd0.png)

**Comment by supriyopaul** [comment]
@Rajendra-R This is the expected behaviour. The level "info" here is at docker container level (in native docker format) , you can see similar logs when a container is created or stopped and we do not intend to make any changes over there, the logs of your process  running inside the container is inside msg.messege with some additional fields added by `docker-file-log-driver` like 'tag', 'extra', 'host', etc.

To simplify, 2 different log levels are expected, in this case, the `debug` logs of your process wrapped by docker `info` logs

**Comment by ghost** [comment]
@supriyopaul As per your comment, the higher `log-level` is not related to Actual log message it is related to docker. so we can close this ticket.
